// Code generated by protoc-gen-go.
// source: src/github.com/jaeyeom/crawler/fetcher/fetch_info.proto
// DO NOT EDIT!

/*
Package fetcher is a generated protocol buffer package.

It is generated from these files:
	src/github.com/jaeyeom/crawler/fetcher/fetch_info.proto

It has these top-level messages:
	FetchInfo
*/
package fetcher

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FetchInfo struct {
	Url              *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Contents         []byte  `protobuf:"bytes,2,opt,name=contents" json:"contents,omitempty"`
	StatusCode       *int32  `protobuf:"varint,3,opt,name=status_code" json:"status_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FetchInfo) Reset()         { *m = FetchInfo{} }
func (m *FetchInfo) String() string { return proto.CompactTextString(m) }
func (*FetchInfo) ProtoMessage()    {}

func (m *FetchInfo) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *FetchInfo) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *FetchInfo) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func init() {
}
